import { createSlice } from "@reduxjs/toolkit";

// Create a slice for tweets with initial state and reducers
const tweetSlice = createSlice({
    name: "tweet", // Name of the slice
    initialState: {
        tweets: null, // State to hold tweets
        refresh: false, // State to manage refresh status
        isActive: true // State to manage active status
    },
    reducers: {
        // Reducer to set all tweets
        getAllTweets: (state, action) => {
            state.tweets = action.payload;
        },
        // Reducer to toggle refresh state
        getRefresh: (state) => {
            state.refresh = !state.refresh;
        },
        // Reducer to set active status
        getIsActive: (state, action) => {
            state.isActive = action.payload;
        }
    }
});

// Export actions generated by createSlice
export const { getAllTweets, getRefresh, getIsActive } = tweetSlice.actions;

// Export the reducer to be used in the store
export default tweetSlice.reducer;
