import { createSlice } from "@reduxjs/toolkit";

// Create a slice for user with initial state and reducers
const userSlice = createSlice({
    name: "user", // Name of the slice
    initialState: {
        user: null, // State to hold the current user's data
        otherUsers: null, // State to hold other users' data
        profile: null // State to hold the profile data
    },
    reducers: {
        // Reducer to set the current user's data
        getUser: (state, action) => {
            state.user = action.payload;
        },
        // Reducer to set other users' data
        getOtherUsers: (state, action) => {
            state.otherUsers = action.payload;
        },
        // Reducer to set the profile data
        getMyProfile: (state, action) => {
            state.profile = action.payload;
        },
        // Reducer to update following status
        followingUpdate: (state, action) => {
            // Unfollow user if already following
            if (state.user.following.includes(action.payload)) {
                state.user.following = state.user.following.filter((itemId) => {
                    return itemId !== action.payload;
                });
            } else {
                // Follow user
                state.user.following.push(action.payload);
            }
        }
    }
});

// Export actions generated by createSlice
export const { getUser, getOtherUsers, getMyProfile, followingUpdate } = userSlice.actions;

// Export the reducer to be used in the store
export default userSlice.reducer;
